# Generated by Django 4.1.2 on 2022-10-25 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Internal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=10)),
                (
                    "destination",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="(RECHARGE\\sEXPRESS\\s.+)"
                            )
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Armencho mihat gri sti",
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "percent",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ]
                    ),
                ),
                ("quantity_after_percent", models.FloatField()),
                ("net_a_payer", models.FloatField()),
                ("advance_payment", models.CharField(blank=True, max_length=10)),
                ("total_payment", models.FloatField()),
                ("total_tax", models.FloatField()),
                ("total_payment_after_tax", models.FloatField()),
            ],
        ),
    ]
