# Generated by Django 4.1.2 on 2022-12-06 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_internal_percent_alter_internal_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal',
            name='destination',
            field=models.CharField(
                default='RECHARGE EXPRESS 1234',
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(regex='(RECHARGE\\sEXPRESS\\s.+)')
                ],
            ),
        ),
        migrations.AlterField(
            model_name='internal',
            name='total_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='total_payment_after_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='total_tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
